model_type : 'Sequential'
MAX_ITEM_LIST_LENGTH : 50
ITEM_LIST_FIELD : 'item_list_field'
train_batch_size: 512
c_n_layers: 1
c_n_heads: 1
s_n_layers: 2
s_n_heads: 1
mm_n_layers: 2
mm_n_heads: 1
gcn_n_layers: 2
hidden_size: 64
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: ['CE']



reg_weight: 0
learning_rate: 1e-03

hyper_parameters: ["loss_type"]